if(!dojo._hasResource["translations.Vouchers"]){ //_hasResource checks added by build. Do not use _hasResource directly in your code.
    dojo._hasResource["tranlations.Vouchers"] = true;
    dojo.provide("translations.Vouchers");

(function(){

    translations.Vouchers.phrases     = {
         'Filter': { 
            'de_DE' : 'Filter',
            'es_ES' : 'Filtro',
            'af_ZA' : 'Deursif',
            'fr_FR' : 'Filtre',
            'ms_MY' : 'Tapis',
            'nl_NL' : 'Filter',
            'id_ID' : 'Saring',
            'th_TH' : 'ตัวกรอง',
            'pt_BR' : 'Filtro',
            'da_DK' : 'Filter',
            'it_IT' : 'Filtro',
	        'fa_IR' : 'فیلتر'
           },
         'Field': { 
            'de_DE' : 'Feld',
            'es_ES' : 'Campo',
            'af_ZA' : 'Veld',
            'fr_FR' : 'Champ',
            'ms_MY' : 'Medan',
            'nl_NL' : 'Veld',
            'id_ID' : 'Daerah',
            'th_TH' : 'ฟิลด์',
            'pt_BR' : 'Campo',
            'da_DK' : 'Felt',
            'it_IT' : 'Campo',
	        'fa_IR' : 'فیلد'
           },
         'Voucher': { 
            'de_DE' : 'Ticket',
            'es_ES' : 'Vale',
            'af_ZA' : 'Koepon',
            'fr_FR' : 'Coupon',
            'ms_MY' : 'Baucer',
            'nl_NL' : 'Coupon',
            'id_ID' : 'Voucher',
            'th_TH' : 'คูปอง',
            'pt_BR' : 'Voucher',
            'da_DK' : 'Adgangskort',
            'it_IT' : 'Voucher',
            'fa_IR' : 'کوپن'
           },
        'Profile': { 
            'de_DE' : 'Profil',
            'es_ES' : 'Perfil',
            'af_ZA' : 'Profiel',
            'fr_FR' : 'Profil',
            'ms_MY' : 'Profail',
            'nl_NL' : 'Profiel',
            'id_ID' : 'Profile',
            'th_TH' : 'กลุ่มผู้ใช้',
            'pt_BR' : 'Perfil',
            'da_DK' : 'Profil',
            'it_IT' : 'Profilo',
            'fa_IR' : 'پروفایل'
           },
        'Creator': { 
            'de_DE' : 'Ersteller',
            'es_ES' : 'Creador',
            'af_ZA' : 'Geskep deur',
            'fr_FR' : 'Créateur',
            'ms_MY' : 'Pencipta',
            'nl_NL' : 'Aangemaakt door',
            'id_ID' : 'Pembuat',
            'th_TH' : 'ผู้สร้าง',
            'pt_BR' : 'Criador',
            'da_DK' : 'Ophavsmand',
            'it_IT' : 'Creato da',
            'fa_IR' : 'سازنده'
           },
        'Realm': { 
            'de_DE' : 'Standort',
            'es_ES' : 'Lugar',
            'af_ZA' : 'Gebied',
            'fr_FR' : 'Domaine',
            'ms_MY' : 'Cawangan',
            'nl_NL' : 'Locatie',
            'id_ID' : 'Realm',
            'th_TH' : 'เขตพื้นที่',
            'pt_BR' : 'Zona',
            'da_DK' : 'Hotspot zone',
            'it_IT' : 'Dominio',
            'fa_IR' : 'ناحیه'
           },
        'Created': { 
            'de_DE' : 'Erstellt',
            'es_ES' : 'Creado',
            'af_ZA' : 'Geskep',
            'fr_FR' : 'Crée',
            'ms_MY' : 'Dicipta',
            'nl_NL' : 'Aangemaakt',
            'id_ID' : 'Dibuat',
            'th_TH' : 'สร้างเมื่อ',
            'pt_BR' : 'Criado',
            'da_DK' : 'Oprettet',
            'it_IT' : 'Creato',
	        'fa_IR' : 'ساخته شد'
           },
        'Status': { 
            'de_DE' : 'Status',
            'es_ES' : 'Estado',
            'af_ZA' : 'Stand',
            'fr_FR' : 'Status',
            'ms_MY' : 'Status',
            'nl_NL' : 'Status',
            'id_ID' : 'Status',
            'th_TH' : 'สถานะ',
            'pt_BR' : 'Estado',
            'da_DK' : 'Status',
            'it_IT' : 'Stato',
            'fa_IR' : 'وضعیت'
           },
        'Result count': { 
            'de_DE' : 'Summe',
            'es_ES' : 'Número',
            'af_ZA' : 'Aantal',
            'fr_FR' : 'Résultat total',
            'ms_MY' : 'Bilangan hasil',
            'nl_NL' : 'Aantal',
            'id_ID' : 'Jumlah',
            'th_TH' : 'จำนวนผลลัพธ์',
            'pt_BR' : 'Total',
            'da_DK' : 'Antal',
            'it_IT' : 'Risultato',
            'fa_IR' : 'تعداد نتایج'
           },
        'No Selection made': {
            'de_DE' : 'Keine Auswahl getroffen',
            'es_ES' : 'No ha seleccionado nada',
            'af_ZA' : 'Niks gekies nie',
            'fr_FR' : 'Aucun élément sélectionné',
            'ms_MY' : 'Tiada pilihan dibuat',
            'nl_NL' : 'Maak eerst een selectie',
            'id_ID' : 'Anda belum memilih',
            'th_TH' : 'ไม่มีการเลือก',
            'pt_BR' : 'Não há nada selecionado',
            'da_DK' : 'Intet valgt',
            'it_IT' : 'Nessuna selezione',
            'fa_IR' : 'هیچ انتخابی انجام نشده'
           },
        'New Voucher': { 
            'de_DE' : 'Neues Ticket',
            'es_ES' : 'Nuevo Vale',
            'af_ZA' : 'Nuwe Koepon',
            'fr_FR' : 'Nouveau coupon',
            'ms_MY' : 'Baucer baru',
            'nl_NL' : 'Nieuwe coupon',
            'id_ID' : 'Voucher baru',
            'th_TH' : 'เพิ่มคูปอง',
            'pt_BR' : 'Novo Voucher',
            'da_DK' : 'Nyt adgangskort',
            'it_IT' : 'Nuovo voucher',
            'fa_IR' : 'کوپن جدید'
           },
        'Precede String': { 
            'de_DE' : 'Zusatzname',
            'es_ES' : 'Cadena Prefijo',
            'af_ZA' : 'Voorafgaan name',
            'fr_FR' : 'Préfixe',
            'ms_MY' : 'Kata Awalan',
            'nl_NL' : 'Voorloop-tekenreeks',
            'id_ID' : 'Kode awal',
            'th_TH' : 'คำนำหน้า',
            'pt_BR' : 'Prefixo',
            'da_DK' : 'Tilføj tekststreng forrest',
            'it_IT' : 'Prefisso',
            'fa_IR' : 'رشته پیشوندی'
           },
        'day from first log-in' : {
            'de_DE' : 'Tag ab erster Anmeldung',
            'es_ES' : 'día desde la primera conexión',
            'af_ZA' : 'dag vanaf eerste inteken',
            'fr_FR' : 'jour depuis le premier login',
            'ms_MY' : 'hari dari log-masuk pertama',
            'nl_NL' : 'dag vanaf eerste login',
            'id_ID' : 'Hari setelah login',
            'th_TH' : 'วัน นับจากเริ่มใช้งาน',
            'pt_BR' : 'dia desde o primeiro login',
            'da_DK' : 'dag fra første anvendelse',
            'it_IT' : 'Giorno dal primo accesso',
            'fa_IR' : 'روز از اولین ورود'
           },
        'days from first log-in' : {
            'de_DE' : 'Tage ab erster Anmeldung',
            'es_ES' : 'días desde la primera conexión',
            'af_ZA' : 'dae vanaf eerste inteken',
            'fr_FR' : 'jours depuis le premier login',
            'ms_MY' : 'hari dari log-masuk pertama',
            'nl_NL' : 'dagen vanaf eerste login',
            'id_ID' : 'Hari setelah login',
            'th_TH' : 'วัน นับจากเริ่มใช้งาน',
            'pt_BR' : 'dias desde o primeiro login',
            'da_DK' : 'dage fra første anvendelse',
            'it_IT' : 'Giorni dal primo accesso',
            'fa_IR' : 'روزهای از اولین ورود'
           },
        'Valid for' : {
            'de_DE' : 'Gueltig fuer',
            'es_ES' : 'Válido durante',
            'af_ZA' : 'Geldig vir',
            'fr_FR' : 'Valide pour',
            'ms_MY' : 'Sah untuk',
            'nl_NL' : 'Geldigheid',
            'id_ID' : 'Berlaku sampai',
            'th_TH' : 'มีอายุการใช้งาน',
            'pt_BR' : 'Válido durante',
            'da_DK' : 'Gyldig til',
            'it_IT' : 'Valido per',
            'fa_IR' : 'معتبر برای'
           },
        'Expiry date': { 
            'de_DE' : 'Ablaufdatum',
            'es_ES' : 'Fecha de Expiración',
            'af_ZA' : 'Vervaldatum',
            'fr_FR' : "Date d'expiration",
            'ms_MY' : 'Tarikh luput',
            'nl_NL' : 'Vervaldatum',
            'id_ID' : 'Gunakan voucher sebelum',
            'th_TH' : 'วันที่หมดอายุ',
            'pt_BR' : 'Data de expiração',
            'da_DK' : 'Udløbsdato',
            'it_IT' : 'Data di scadenza',
            'fa_IR' : 'تاریخ انقضا'
           },
        'Save' : {
            'de_DE' : 'Speichern',
            'es_ES' : 'Guardar',
            'af_ZA' : 'Stoor',
            'fr_FR' : 'Sauver',
            'ms_MY' : 'Simpan',
            'nl_NL' : 'Opslaan',
            'id_ID' : 'Simpan',
            'th_TH' : 'บันทึก',
            'pt_BR' : 'Salvar',
            'da_DK' : 'Gem',
            'it_IT' : 'Salva',
            'fa_IR' : 'ذخیره'
           },
        'New voucher created OK' : {
            'de_DE' : 'Neues Ticket erstellt',
            'es_ES' : 'Nuevo vale creado OK',
            'af_ZA' : 'Nuwe koepon is geskep',
            'fr_FR' : 'Nouveau coupon crée',
            'ms_MY' : 'Berjaya mencipta Baucer baru',
            'nl_NL' : 'Nieuwe coupon succesvol aangemaakt',
            'id_ID' : 'Pembuatan voucher berhasil',
            'th_TH' : 'สร้างคูปองใหม่เรียบร้อยแล้ว',
            'pt_BR' : 'Novo voucher criado OK',
            'da_DK' : 'Nyt adgangskort oprettet!',
            'it_IT' : 'Nuovo voucher creato!',
            'fa_IR' : 'کوپن جدید با موفقیت ساخته شد'
           },
        'Problems creating voucher' : {
            'de_DE' : 'Problem beim erstellen Ticket',
            'es_ES' : 'Problemas creando vale',
            'af_ZA' : 'Probleme met die skep van koepon',
            'fr_FR' : 'Des problèmes sont survenus lors de la création du coupon',
            'ms_MY' : 'Gagal mencipta Baucer baru',
            'nl_NL' : 'Nieuwe coupon aanmaken mislukt',
            'id_ID' : 'bermasalah dalam Pembuatan voucher',
            'th_TH' : 'มีปัญหาในการสร้างคูปอง',
            'pt_BR' : 'Problemas ao criar o voucher',
            'da_DK' : 'Problemer med at oprette adgangskort',
            'it_IT' : 'Problemi durante la creazione del voucher',
            'fa_IR' : 'ایرادات ایجاد کوپن'
           },
        'Removing Vouchers': {
            'de_DE' : 'Ticket entfernen',
            'es_ES' : 'Eliminando Vales',
            'af_ZA' : 'Verwyder Koeponne',
            'fr_FR' : 'Suppression des coupons en cours',
            'ms_MY' : 'Membuang Baucer',
            'nl_NL' : 'Coupons verwijderen',
            'id_ID' : 'Hapus Voucher',
            'th_TH' : 'ลบคูปอง',
            'pt_BR' : 'Removendo vouchers',
            'da_DK' : 'Fjerner adgangskort...',
            'it_IT' : 'Eliminazione voucher',
            'fa_IR' : 'حذف کردن کوپنها'
           },
        'Voucher(s) Removed OK': {
            'de_DE' : 'Ticket(s) entfernt',
            'es_ES' : 'Vale(s) Eliminado(s) OK',
            'af_ZA' : 'Koeponne is verwyder',
            'fr_FR' : 'Coupon(s) supprimé(s) avec succès',
            'ms_MY' : 'Berjaya membuang Baucer',
            'nl_NL' : 'Coupons succesvol verwijderd',
            'id_ID' : 'penghapusan Voucher berhasil',
            'th_TH' : 'คูปองถูกลบแล้ว',
            'pt_BR' : 'Voucher(s) removido(s) OK',
            'da_DK' : 'Adgangskort fjernet!',
            'it_IT' : 'Voucher rimosso(i)',
            'fa_IR' : 'کوپنها با موفقیت حذف شدند'
           },
        'Opening detail for': {
            'de_DE' : 'Details &ouml;ffnen f&uuml;r ',
            'es_ES' : 'Abriendo detalles de',
            'af_ZA' : 'Wys Detail vir',
            'fr_FR' : 'Ouverture des détails pour',
            'ms_MY' : 'Membuka perincian untuk',
            'nl_NL' : 'Details openen voor',
            'id_ID' : 'Buka detail untuk',
            'th_TH' : 'เปิดข้อมูลสำหรับ',
            'pt_BR' : 'Abrindo detalhes de',
            'da_DK' : 'Åbner detaljer for',
            'it_IT' : 'Apri dettagli per',
            'fa_IR' : 'باز کردن جزئیات برای'
           },
        'new': {
            'de_DE' : 'neu',
            'es_ES' : 'nuevo',
            'af_ZA' : 'nuut',
            'fr_FR' : 'nouveau',
            'ms_MY' : 'baru',
            'nl_NL' : 'nieuw',
            'id_ID' : 'Baru',
            'th_TH' : 'เพิ่มใหม่',
            'pt_BR' : 'novo',
            'da_DK' : 'ny',
            'it_IT' : 'nuovo',
            'fa_IR' : 'جدید'
           },
        'used': {
            'de_DE' : 'verwendet',
            'es_ES' : 'usado',
            'af_ZA' : 'reeds gebruik',
            'fr_FR' : 'utilisé',
            'ms_MY' : 'diguna',
            'nl_NL' : 'verbruikt',
            'id_ID' : 'terpakai',
            'th_TH' : 'ใช้ไป',
            'pt_BR' : 'usado',
            'da_DK' : 'benyttet',
            'it_IT' : 'usati',
            'fa_IR' : 'استفاده شده'
           },
        'depleted': {
            'de_DE' : 'verbraucht',
            'es_ES' : 'agotado',
            'af_ZA' : 'uitgeput',
            'fr_FR' : 'épuisé',
            'ms_MY' : 'habis',
            'nl_NL' : 'vervallen',
            'id_ID' : 'Habis',
            'th_TH' : 'ถูกทำให้หมดลง',
            'pt_BR' : 'esgotados',
            'da_DK' : 'udtømt',
            'it_IT' : 'ridotto',
            'fa_IR' : 'خالی شده'
           },
        'Select Format' :{
            'de_DE' : 'Format w&auml;hlen',
            'es_ES' : 'Seleccionar Formato',
            'af_ZA' : 'Kies Formaat',
            'fr_FR' : 'Sélectionner le format',
            'ms_MY' : 'Pilih Format',
            'nl_NL' : 'Kies formaat',
            'id_ID' : 'Pilih format',
            'th_TH' : 'เลือกรูปแบบ',
            'pt_BR' : 'Selecionar o Formato',
            'da_DK' : 'Vælg format',
            'it_IT' : 'Seleziona formato',
            'fa_IR' : 'لطفا قالب را انتخاب کنید'
           },
        'PDF Output Format' :{
            'de_DE' : 'PDF Ausgabe Format',
            'es_ES' : 'Formato de Salida PDF',
            'af_ZA' : 'Formaat van PDF',
            'fr_FR' : 'Format de sortie PDF',
            'ms_MY' : 'Format Output PDF',
            'nl_NL' : 'PDF-formaat',
            'id_ID' : 'Format output PDF',
            'th_TH' : 'รูปแบบ PDF',
            'pt_BR' : 'Formato de Saída PDF',
            'da_DK' : 'PDF format',
            'it_IT' : 'Formato PDF',
            'fa_IR' : 'فرمت خروجی pdf'
           },
        'Language' : {
            'de_DE' : 'Sprache',
            'es_ES' : 'Idioma',
            'af_ZA' : 'Taalvoorkeur',
            'fr_FR' : 'Langue',
            'ms_MY' : 'Bahasa',
            'nl_NL' : 'Taal',
            'id_ID' : 'Bahasa',
            'th_TH' : 'ภาษา',
            'pt_BR' : 'Idioma',
            'da_DK' : 'Sprog',
            'it_IT' : 'Lingua',
            'fa_IR' : 'زبان'
           },
        'OK':{
            'de_DE' : 'OK',
            'es_ES' : 'OK',
            'af_ZA' : 'OK',
            'fr_FR' : 'OK',
            'ms_MY' : 'OK',
            'nl_NL' : 'OK',
            'id_ID' : 'OK',
            'th_TH' : 'ตกลง',
            'pt_BR' : 'OK',
            'da_DK' : 'OK',
            'it_IT' : 'OK',
            'fa_IR' : 'تایید'
           }
    };

})();//(function(){

}
