

if(!dojo._hasResource["translations.Nas"]){ //_hasResource checks added by build. Do not use _hasResource directly in your code.
    dojo._hasResource["tranlations.Nas"] = true;
    dojo.provide("translations.Nas");

(function(){

    translations.Nas.phrases     = {
        'Filter': {
            'de_DE' : 'Filter',
            'es_ES' : 'Filtro', 
            'af_ZA' : 'Deursif',
            'fr_FR' : 'Filtre',
            'ms_MY' : 'Tapis',
            'nl_NL' : 'Filter',
            'id_ID' : 'Saring',
            'th_TH' : 'ตัวกรอง',
            'pt_BR' : 'Filtro',
            'da_DK' : 'Filter',
            'it_IT' : 'Filtro'
           },
        'Field': { 
            'de_DE' : 'Feld',
            'es_ES' : 'Campo',
            'af_ZA' : 'Veld',
            'fr_FR' : 'Champs',
            'ms_MY' : 'Medan',
            'nl_NL' : 'Veld',
            'id_ID' : 'Daerah',
            'th_TH' : 'ฟิลด์',
            'pt_BR' : 'Campo',
            'da_DK' : 'Felt',
            'it_IT' : 'Campo'
           },
        'IP Address': { 
            'de_DE' : 'IP Adresse',
            'es_ES' : 'Dirección IP',
            'af_ZA' : 'IP-Adres',
            'fr_FR' : 'Adresse IP',
            'ms_MY' : 'Alamat IP',
            'nl_NL' : 'IP-adres',
            'id_ID' : 'Alamat IP',
            'th_TH' : 'IP Address',
            'pt_BR' : 'Endereço IP',
            'da_DK' : 'IP adresse',
            'it_IT' : 'Indirizzo IP'
           },
        'Name': { 
            'de_DE' : 'Name',
            'es_ES' : 'Nombre',
            'af_ZA' : 'Naam',
            'fr_FR' : 'Nom',
            'ms_MY' : 'Nama',
            'nl_NL' : 'Naam',
            'id_ID' : 'Nama',
            'th_TH' : 'ชื่อ',
            'pt_BR' : 'Nome',
            'da_DK' : 'Navn',
            'it_IT' : 'Nome'
           },
        'Type': { 
            'de_DE' : 'Type',
            'es_ES' : 'Tipo',
            'af_ZA' : 'Tipe',
            'fr_FR' : 'Type',
            'ms_MY' : 'Jenis',
            'nl_NL' : 'Type',
            'id_ID' : 'Type',
            'th_TH' : 'ชนิด',
            'pt_BR' : 'Tipo',
            'da_DK' : 'Type',
            'it_IT' : 'Tipo'
           },
        'Status': { 
            'de_DE' : 'Status',
            'es_ES' : 'Estado',
            'af_ZA' : 'Stand',
            'fr_FR' : 'Statut',
            'ms_MY' : 'Status',
            'nl_NL' : 'Status',
            'id_ID' : 'Status',
            'th_TH' : 'สถานะ',
            'pt_BR' : 'Estado',
            'da_DK' : 'Status',
            'it_IT' : 'Stato'
           },
        'Users Connected': { 
            'de_DE' : 'Benutzer verbunden',
            'es_ES' : 'Usuarios Conectados',
            'af_ZA' : 'Aktiewe gebruikers',
            'fr_FR' : 'Utilisateurs connectés',
            'ms_MY' : 'Pengguna Bersambung',
            'nl_NL' : 'Actieve gebruikers',
            'id_ID' : 'User terhubung',
            'th_TH' : 'ผู้ใช้เชื่อมต่อ',
            'pt_BR' : 'Usuários Conectados',
            'da_DK' : 'Brugere tilsluttet',
            'it_IT' : 'Utenti connessi'
           },
        'Contact Person': { 
            'de_DE' : 'Benutzer kontaktieren',
            'es_ES' : 'Persona de Contacto',
            'af_ZA' : 'Kontak persoon',
            'fr_FR' : 'Contact Person',
            'ms_MY' : 'Hubungi',
            'nl_NL' : 'Contactpersoon',
            'id_ID' : 'Contact person',
            'th_TH' : 'ผู้ติดต่อ',
            'pt_BR' : 'Contato',
            'da_DK' : 'Kontaktperson',
            'it_IT' : 'Persona di riferimento'
           },
        'Realms': { 
            'de_DE' : 'Standort',
            'es_ES' : 'Lugares',
            'af_ZA' : 'Gebiede',
            'fr_FR' : 'Contact Person',
            'ms_MY' : 'Cawangan',
            'nl_NL' : 'Locaties',
            'id_ID' : 'Realm',
            'th_TH' : 'เขตพื้นที่',
            'pt_BR' : 'Zonas',
            'da_DK' : 'Hotspot zone',
            'it_IT' : 'Dominio'
           },
        'Refesh every': { 
            'de_DE' : 'Alle aktualisieren',
            'es_ES' : 'Actualizar cada',
            'af_ZA' : 'Herlaai elke',
            'fr_FR' : 'Réactualiser toutes les',
            'ms_MY' : 'Segarkan setiap',
            'nl_NL' : 'Ververs elke',
            'id_ID' : 'Refresh tiap',
            'th_TH' : 'รีเฟรชทุก ๆ',
            'pt_BR' : 'Atualizar a cada',
            'da_DK' : 'Forny hver',
            'it_IT' : 'Ricarica ogni'
           },
        'seconds': { 
            'de_DE' : 'sekunden',
            'es_ES' : 'segundos',
            'af_ZA' : 'sekondes',
            'fr_FR' : 'secondes',
            'ms_MY' : 'saat',
            'nl_NL' : 'seconden',
            'id_ID' : 'Detik',
            'th_TH' : 'วินาที',
            'pt_BR' : 'segundos',
            'da_DK' : 'sekunder',
            'it_IT' : 'secondi'
           },
        'Result count': { 
            'de_DE' : 'Summe',
            'es_ES' : 'Número',
            'af_ZA' : 'Aantal',
            'fr_FR' : 'Total',
            'ms_MY' : 'Bilangan hasil',
            'nl_NL' : 'Aantal',
            'id_ID' : 'Daerah',
            'th_TH' : 'จำนวนผลลัพธ์',
            'pt_BR' : 'Total',
            'da_DK' : 'Antal',
            'it_IT' : 'Risultato'
           },
        'No Selection made': {
            'de_DE' : 'Keine Auswahl getroffen',
            'es_ES' : 'No ha seleccionado nada',
            'af_ZA' : 'Niks gekies nie',
            'fr_FR' : 'Aucun élément sélectionné',
            'ms_MY' : 'Tiada pilihan dibuat',
            'nl_NL' : 'Maak eerst een selectie',
            'id_ID' : 'Anda belum memilih',
            'th_TH' : 'ไม่มีการเลือก',
            'pt_BR' : 'Não há nada selecionado',
            'da_DK' : 'Intet valgt',
            'it_IT' : 'Nessuna selezione'
           },
        'Deleting NAS Device(s)': {
            'de_DE' : 'NAS Ger&auml;t(e) l&ouml;schen',
            'es_ES' : 'Eliminado Dispositivo(s) NAS',
            'af_ZA' : 'Verwyder NAS-toestel(le)',
            'fr_FR' : 'Equipements NAS en cours de suppression',
            'ms_MY' : 'Memadam Alat NAS',
            'nl_NL' : 'Verwijder NAS-appara(a)t(en)',
            'id_ID' : 'Menghapus perangkat NAS',
            'th_TH' : 'ลบอุปกรณ์ NAS',
            'pt_BR' : 'Deletando Dispositivo(s) NAS',
            'da_DK' : 'Sletter NAS enhed...',
            'it_IT' : 'Eliminazione apparato(i) NAS'
           },
        'Complete': {
            'de_DE' : 'Fertig',
            'es_ES' : 'Completado',
            'af_ZA' : 'Voltooid',
            'fr_FR' : 'Terminé',
            'ms_MY' : 'Selesai',
            'nl_NL' : 'Voltooid',
            'id_ID' : 'Komplit',
            'th_TH' : 'สมบูรณ์',
            'pt_BR' : 'Completo',
            'da_DK' : 'Afsluttet',
            'it_IT' : 'Completato'
           },
        'New NAS Device': {
            'de_DE' : 'Neues NAS Ger&auml;t',
            'es_ES' : 'Nuevo Dispositivo NAS',
            'af_ZA' : 'Nuwe NAS-toestel',
            'fr_FR' : 'Nouvel équipement NAS',
            'ms_MY' : 'Alat NAS baru',
            'nl_NL' : 'Nieuw NAS-apparaat',
            'id_ID' : 'Perangkat NAS Baru',
            'th_TH' : 'เพิ่มอุปกรณ์ NAS',
            'pt_BR' : 'Novo Dispositivo NAS',
            'da_DK' : 'Ny NAS enhed',
            'it_IT' : 'Nuovo apparato NAS'
           },
        'New VPN connected NAS Device': {
            'de_DE' : 'Neu verbundens VPN NAS Ger&auml;t',
            'es_ES' : 'Nuevo Dispositivo NAS conectado por VPN',
            'af_ZA' : 'Nuwe VPN-tipe NAS-toestel',
            'fr_FR' : 'Nouvel équipement NAS connecté par VPN',
            'ms_MY' : 'Alat NAS bersambungan VPN baru',
            'nl_NL' : 'Nieuw NAS-apparaat met VPN-connectie',
            'id_ID' : 'VPN baru terhubung ke perangkat NAS',
            'th_TH' : 'New VPN connected NAS Device',
            'pt_BR' : 'Novo Dispositivo NAS conectado por VPN',
            'da_DK' : 'Ny VPN-forbundet NAS enhed',
            'it_IT' : 'Nuova connessione VPN-NAS'
           },
        'Secret': {
            'de_DE' : 'Passwort',
            'es_ES' : 'Clave Secreta',
            'af_ZA' : 'Geheim',
            'fr_FR' : 'Secret',
            'ms_MY' : 'Secret',
            'nl_NL' : 'Sleutel',
            'id_ID' : 'Secret',
            'th_TH' : 'Secret',
            'pt_BR' : 'Chave Secreta',
            'da_DK' : 'Hemmelig',
            'it_IT' : 'Password'
           },
        'Available to all': {
            'de_DE' : 'Fuer alle Verfuegbar',
            'es_ES' : 'Disponible para todos',
            'af_ZA' : 'Vir almal beskikbaar',
            'fr_FR' : 'Disponible pour tous',
            'ms_MY' : 'Tersedia untuk semua',
            'nl_NL' : 'Algemeen beschikbaar',
            'id_ID' : 'Tersedia untuk semua',
            'th_TH' : 'สามารถใช้ได้กับทั้งหมด',
            'pt_BR' : 'Disponível para todos',
            'da_DK' : 'Til rådighed for alle',
            'it_IT' : 'Disponibile per tutti'
           },
        'Available only to': {
            'de_DE' : 'Verfuegbar nur fuer',
            'es_ES' : 'Disponible solo para',
            'af_ZA' : 'Slegs beskikbaar vir',
            'fr_FR' : 'Disponible seulement pour',
            'ms_MY' : 'Tersedia hanya untuk',
            'nl_NL' : 'Alleen beschikbaar voor',
            'id_ID' : 'Hanya tersedia untuk',
            'th_TH' : 'สามารถใช้ได้เฉพาะ',
            'pt_BR' : 'Disponível somente para',
            'da_DK' : 'Kun til rådighed for',
            'it_IT' : 'Disponibile solo per'
           },
        'Save': {
            'de_DE' : 'Speichern',
            'es_ES' : 'Guardar',
            'af_ZA' : 'Stoor',
            'fr_FR' : 'Sauver',
            'ms_MY' : 'Simpan',
            'nl_NL' : 'Opslaan',
            'id_ID' : 'Simpan',
            'th_TH' : 'บันทึก',
            'pt_BR' : 'Salvar',
            'da_DK' : 'Gem',
            'it_IT' : 'Salva'
           },
        'Created NAS Device' :{
            'de_DE' : 'NAS Ger&auml;t anlegen',
            'es_ES' : 'Dispositivo NAS Creado',
            'af_ZA' : 'NAS-toestel geskep',
            'fr_FR' : "L'équipement NAS a été crée",
            'ms_MY' : 'Berjaya mencipta Alat NAS',
            'nl_NL' : 'NAS-apparaat aangemaakt',
            'id_ID' : 'Buat perangkat NAS',
            'th_TH' : 'เพิ่มอุปกรณ์ NAS แล้ว',
            'pt_BR' : 'Dispositivo NAS criado',
            'da_DK' : 'NAS enhed oprettet',
            'it_IT' : 'Dispositivo NAS creato'
           },
        'Problems creating NAS device' :{
            'de_DE' : 'Probleme beim anlegen des NAS Ger&auml;ts',
            'es_ES' : 'Problemas creando dispositivo NAS',
            'af_ZA' : 'Probleme met skep van NAS-toestel',
            'fr_FR' : "Des problèmes sont survenus lors de la création de l'équipement",
            'ms_MY' : 'Gagal mencipta Alat NAS',
            'nl_NL' : 'NAS-apparaat aanmaken mislukt',
            'id_ID' : 'Bermasalah dalam pembuatan perangkat NAS',
            'th_TH' : 'มีปัญหาในการเพิ่มอุปกรณ์ NAS',
            'pt_BR' : 'Problemas ao criar dispositivo NAS',
            'da_DK' : 'Problemer med at oprette NAS enhed',
            'it_IT' : 'Problemi durante la creazione del dispositivo NAS'
           },
        'Opening detail for': {
            'de_DE' : 'Details &ouml;ffnen f&uuml;r',
            'es_ES' : 'Abriendo detalle de',
            'af_ZA' : 'Wys detail vir',
            'fr_FR' : 'Ouverture en cours des détails pour',
            'ms_MY' : 'Membuka perincian untuk',
            'nl_NL' : 'Details openen voor',
            'id_ID' : 'Buka detail untuk',
            'th_TH' : 'เปิดข้อมูลสำหรับ',
            'pt_BR' : 'Abrindo detalhes de',
            'da_DK' : 'Åbner detaljer for',
            'it_IT' : 'Aggiungi dettagli per'
           },
        'Activate Changes': {
            'de_DE' : 'Aktiviere &Auml;nderungen',
            'es_ES' : 'Activar Cambios',
            'af_ZA' : 'Bekragtig Veranderinge',
            'fr_FR' : 'Activation des changements',
            'ms_MY' : 'Aktifkan Perubahan',
            'nl_NL' : 'Activeer wijzigingen',
            'id_ID' : 'Aktifkan perubahan',
            'th_TH' : 'เปลี่ยนการเปิดใช้งาน',
            'pt_BR' : 'Ativar Alterações',
            'da_DK' : 'Aktivér ændringer',
            'it_IT' : 'Attiva modifiche'
           },
        'Fetching latest' :{
            'de_DE' : 'Hole letztes',
            'es_ES' : 'Buscando ultimo',
            'af_ZA' : 'Verkry die nuutste',
            'fr_FR' : 'Chargement des derniers',
            'ms_MY' : 'Memuatkan yang terbaru',
            'nl_NL' : 'Laatste ophalen',
            'id_ID' : 'Fetching terakhir',
            'th_TH' : 'ดึงมาล่าสุด',
            'pt_BR' : 'Buscando último',
            'da_DK' : 'Henter seneste...',
            'it_IT' : 'Ricerca ultime'
           },
        'data' :{
            'de_DE' : 'daten',
            'es_ES' : 'datos',
            'af_ZA' : 'data',
            'fr_FR' : 'données',
            'ms_MY' : 'data',
            'nl_NL' : 'data',
            'id_ID' : 'data',
            'th_TH' : 'ข้อมูล',
            'pt_BR' : 'dados',
            'da_DK' : 'data',
            'it_IT' : 'data'
           }
    };

})();//(function(){

}
